=== mazensharkawy/XMLDatabase/src/eg/edu/alexu/csd/oop/db/test.xsd
<?xml version="1.0" encoding="UTF-8"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified"><xsd:element name="table"><xsd:complexType><xsd:sequence><xsd:element name="row" maxOccurs="unbounded"><xsd:complexType><xsd:sequence><xsd:element name="Course" type="xsd:string"></xsd:element><xsd:element name="Grade" type="xsd:string"></xsd:element><xsd:element name="Marks" type="xsd:string"></xsd:element> </xsd:sequence></xsd:complexType></xsd:element></xsd:sequence></xsd:complexType></xsd:element></xsd:schema>

=== mazensharkawy/XMLDatabase/src/eg/edu/alexu/csd/oop/db/test.xml
<?xml version="1.0" encoding="UTF-8"?><table xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com file:///C:/Users/HP-/Documents/NetBeansProjects/Database/src/eg/edu/alexu/csd/oop/db/test.xsd"><row><Course>varchar</Course><Grade>varchar</Grade><Marks>int</Marks></row><row><Course>Programming_II</Course><Grade>A</Grade><Marks>0</Marks></row><row><Course>Programming_II</Course><Grade>A</Grade><Marks>0</Marks></row><row><Course>Programming_II</Course><Grade>A</Grade><Marks>0</Marks></row><row><Course>Programming_II</Course><Grade>A</Grade><Marks>0</Marks></row><row><Course>Programming_II</Course><Grade>A</Grade><Marks>0</Marks></row><row><Course>Programming_II</Course><Grade>A</Grade><Marks>0</Marks></row></table>
